/* Generated By:JavaCC: Do not edit this line. BNParseConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BNParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROB_OF = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int CONDITIONED_ON = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int CPT_BEGIN = 11;
  /** RegularExpression Id. */
  int CPT_END = 12;
  /** RegularExpression Id. */
  int EVIDENCE = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int PVALUE = 15;
  /** RegularExpression Id. */
  int VARNAME = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"P\"",
    "\"(\"",
    "\"|\"",
    "\",\"",
    "\")\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"evidence\"",
    "\"-\"",
    "<PVALUE>",
    "<VARNAME>",
    "<LETTER>",
    "<DIGIT>",
  };

}
